name: go-microservice-buildwithangga
services:
  field-service:
    container_name: field-service
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    env_file:
      - .env


